name: Workflow for Codecov
on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Install cargo-criterion
      #   uses: Cryptex-github/cached-cargo-install@main
      #   with:
      #     crate-name: cargo-criterion
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: crxst # optional
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
